layer.conf: add meta-virtualization to LAYERDEPENDS
Issue: LINUXEXEC-23251

Fix the below yocto compliance issue:
  ERROR: Nothing PROVIDES 'virtual/libibverbs' (but /build/layers/meta-cloud-services/recipes-extended/librdmacm/librdmacm_1.1.0.bb, /build/layers/meta-cloud-services/recipes-extended/glusterfs/glusterfs_6.1.bb DEPENDS on or otherwise requires it). Close matches:
    virtual/libiconv
    virtual/librpc
    virtual/libsdl
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'librdmacm', 'virtual/libibverbs']

(LOCAL REV: NOT UPSTREAM) -- send to yocto 20221129

Summary: There were 2 ERROR messages, returning a non-zero exit code.

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>